name: "Release to Puppet Forge"

on:
  push:
    tags: ["v[0-9]+[.][0-9]+[.][0-9]+"]

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        task:
        - "spec"
        - "lint"
        - "metadata_lint"
        - "syntax"
        - "rubocop"
    steps:
    - uses: "actions/checkout@v4"
    - name: "rake ${{ matrix.task }}"
      run: |
        docker run --rm `docker build -q .` rake ${{ matrix.task }}

  release:
    runs-on: "ubuntu-latest"
    needs: "test"
    secrets: "inherit"
    steps:
    - uses: "actions/checkout@v4"
    - name: "pdk build"
      uses: "docker://puppet/pdk:3.0.0.0"
      with:
        args: "build"
    - name: "pdk publish"
      uses: "docker://puppet/pdk:3.0.0.0"
      with:
        args: "release publish --forge-token ${{ secrets.FORGE_API_KEY }} --force"
